### ISSUE TITLE
ng test fails

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing-UI#45]
Running ng tests results in 12 FAILED. Need to further investigate if these are true failures or tests are old and need fixing.

```
Chrome 92.0.4515 (Mac OS X 10.15.7): Executed 15 of 15 (12 FAILED) (0 secs / 0.556 secs)
Chrome 92.0.4515 (Mac OS X 10.15.7) AuthenticatedUserGuard should ... FAILED
        NullInjectorError: StaticInjectorError(DynamicTestModule)[AuthenticatedUserGuard -> Router]: 
          StaticInjectorError(Platform: core)[AuthenticatedUserGuard -> Router]: 
            NullInjectorError: No provider for Router!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'AuthenticatedUserGuard', Function ] })
            at <Jasmine>
            at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:855:1)
            at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
            at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
            at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30393:1)
            at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:31578:1)
Chrome 92.0.4515 (Mac OS X 10.15.7): Executed 15 of 15 (12 FAILED) (0.683 secs / 0.556 secs)
TOTAL: 12 FAILED, 3 SUCCESS
TOTAL: 12 FAILED, 3 SUCCESS
```

**Comment by tumit** [comment]
Can I take this issue ?

**Comment by tumit** [comment]
I create PR https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/81

**Comment by demilolu** [comment]
completed by: #81
